name: frontend-cd
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - 'starter/frontend/**'

env:
  AWS_REGION: 'us-east-1'


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: lint
      run: npm --prefix starter/frontend install && npm --prefix starter/frontend run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: lint
      run: npm --prefix starter/frontend install && CI=true npm --prefix starter/frontend test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:

    # Step 1: Checkout to the new code
    - name: Checkout
      uses: actions/checkout@v3

    # Step 2: Build the dependencies 
    - name: build
      run: npm --prefix starter/frontend install && CI=true npm --prefix starter/frontend run build

    # Step 3: Build image  
    - name: Build Docker image
      env:
        BACKEND_ENDPOINT: ${{ secrets.BACKEND_ENDPOINT }}
      run: |
        cd starter/frontend && docker build --build-arg=REACT_APP_MOVIE_API_URL=$BACKEND_ENDPOINT -t my-frontend-app:${{ github.sha }} .
      
    # Step 4: Configure the aws credentials
    - name: set aws credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    
    # Step 5: Login to docker
    - name: docker login
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 6: Push image to AWS ECR
    - name: Push Docker image to ECR
      run: |
        IMAGE_URI=$(aws ecr describe-repositories --repository-names frontend --region us-east-1 --query 'repositories[0].repositoryUri' --output text)
        docker tag my-frontend-app:${{ github.sha }} $IMAGE_URI:${{ github.sha }}
        docker push $IMAGE_URI:${{ github.sha }}

    # Step 7: Install Kustomize
    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    # Step 8: Configure kubeconfig for EKS
    - name: Configure kubeconfig for EKS
      run: aws eks update-kubeconfig --region us-east-1 --name cluster
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Step 9: Update Kubernetes Manifests with New Image
    - name: Update image in Kubernetes manifests
      working-directory: starter/frontend/k8s
      run: |
        IMAGE_URI=$(aws ecr describe-repositories --repository-names backend --region us-east-1 --query 'repositories[0].repositoryUri' --output text)
        kustomize edit set image frontend=$IMAGE_URI:${{ github.sha }}

    # Step 10: Deploy to Kubernetes Cluster
    - name: Deploy to Kubernetes
      working-directory: starter/frontend/k8s
      run: kustomize build | kubectl apply -f -

